### ISSUE TITLE
java.lang.NoSuchMethodError after update

### ISSUE THREAD

**Issue by tuxmaster5000** [jenkinsci/oic-auth-plugin#393] opened 2024-09-10 05:03 UTC
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```
Jenkins: 2.475
OS: Linux - 5.14.0-427.33.1.el9_4.x86_64
Java: 21.0.4 - Red Hat, Inc. (OpenJDK 64-Bit Server VM)
---
active-directory:2.36
analysis-model-api:12.4.0
antisamy-markup-formatter:162.v0e6ec0fcfcf6
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
apache-httpcomponents-client-5-api:5.3.1-110.v77252fb_d4da_5
asm-api:9.7-33.v4d23ef79fcc8
atlassian-bitbucket-server-integration:4.0.0
authentication-tokens:1.119.v50285141b_7e1
aws-credentials:231.v08a_59f17d742
aws-java-sdk-ec2:1.12.767-467.vb_e93f0c614b_6
aws-java-sdk-minimal:1.12.767-467.vb_e93f0c614b_6
bootstrap5-api:5.3.3-1
bouncycastle-api:2.30.1.78.1-248.ve27176eb_46cb_
branch-api:2.1178.v969d9eb_c728e
build-timeout:1.33
caffeine-api:3.1.8-133.v17b_1ff2e0599
checks-api:2.2.1
cloudbees-folder:6.942.vb_43318a_156b_2
command-launcher:115.vd8b_301cc15d0
commons-lang3-api:3.17.0-84.vb_b_938040b_078
commons-text-api:1.12.0-129.v99a_50df237f7
credentials:1371.vfee6b_095f0a_3
credentials-binding:681.vf91669a_32e45
data-tables-api:2.1.6-1
display-url-api:2.204.vf6fddd8a_8b_e9
docker-commons:443.v921729d5611d
docker-workflow:580.vc0c340686b_54
durable-task:568.v8fb_5c57e8417
echarts-api:5.5.1-1
eddsa-api:0.3.0-4.v84c6f0f4969e
email-ext:1814.v404722f34263
external-monitor-job:215.v2e88e894db_f8
favorite:2.221.v19ca_666b_62f5
font-awesome-api:6.6.0-2
forensics-api:2.5.0
git:5.4.1
git-client:5.0.0
git-forensics:2.2.0
git-server:126.v0d945d8d2b_39
gson-api:2.11.0-41.v019fcf6125dc
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
htmlpublisher:1.36
instance-identity:185.v303dc7c645f9
ionicons-api:74.v93d5eb_813d5f
jackson2-api:2.17.0-379.v02de8ec9f64c
jakarta-activation-api:2.1.3-1
jakarta-mail-api:2.1.3-1
javax-activation-api:1.2.0-7
javax-mail-api:1.6.2-10
jaxb:2.3.9-1
jdk-tool:80.v8a_dee33ed6f0
jenkins-design-language:1.27.14
joda-time-api:2.12.7-29.v5a_b_e3a_82269a_
jquery3-api:3.7.1-2
jsch:0.2.16-86.v42e010d9484b_
json-api:20240303-41.v94e11e6de726
json-path-api:2.9.0-58.v62e3e85b_a_655
junit:1296.vb_f538b_c88630
ldap:733.vd3700c27b_043
lockable-resources:1301.v0e3b_da_4b_4462
mailer:472.vf7c289a_4b_420
matrix-auth:3.2.2
matrix-project:832.va_66e270d2946
mina-sshd-api-common:2.13.2-125.v200281b_61d59
mina-sshd-api-core:2.13.2-125.v200281b_61d59
nodelabelparameter:1.12.0
oic-auth:4.331.vd925b_f76f3a_c
pam-auth:1.11
periodicbackup:2.0
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-graph-analysis:216.vfd8b_ece330ca_
pipeline-groovy-lib:730.ve57b_34648c63
pipeline-input-step:495.ve9c153f6067b_
pipeline-milestone-step:119.vdfdc43fc3b_9a_
pipeline-model-api:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-definition:2.2214.vb_b_34b_2ea_9b_83
pipeline-model-extensions:2.2214.vb_b_34b_2ea_9b_83
pipeline-rest-api:2.34
pipeline-stage-step:312.v8cd10304c27a_
pipeline-stage-tags-metadata:2.2214.vb_b_34b_2ea_9b_83
pipeline-stage-view:2.34
plain-credentials:183.va_de8f1dd5a_2b_
plugin-util-api:4.1.0
prism-api:1.29.0-17
pubsub-light:1.18
pyenv-pipeline:2.1.2
resource-disposer:0.23
role-strategy:743.v142ea_b_d5f1d3
saferestart:0.7
scm-api:696.v778d637b_a_762
script-security:1358.vb_26663c13537
sidebar-update-notification:1.1.0
snakeyaml-api:2.3-123.v13484c65210a_
sse-gateway:1.27
ssh-credentials:343.v884f71d78167
ssh-slaves:2.973.v0fa_8c0dea_f9f
sshd:3.330.vc866a_8389b_58
structs:338.v848422169819
timestamper:1.27
token-macro:400.v35420b_922dcb_
trilead-api:2.147.vb_73cc728a_32e
variant:60.v7290fc0eb_b_cd
warnings-ng:11.4.1
workflow-aggregator:600.vb_57cdd26fdd7
workflow-api:1336.vee415d95c521
workflow-basic-steps:1058.vcb_fc1e3a_21a_9
workflow-cps:3961.ve48ee2c44a_b_3
workflow-durable-task-step:1371.vb_7cec8f3b_95e
workflow-job:1436.vfa_244484591f
workflow-multibranch:795.ve0cb_1f45ca_9a_
workflow-scm-step:427.v4ca_6512e7df1
workflow-step-api:678.v3ee58b_469476
workflow-support:920.v59f71ce16f04
ws-cleanup:0.46
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Rocky 9.4

### Reproduction steps

Update to the last version

### Expected Results

Working add on

### Actual Results

Java error:
```
2024-09-10T06:57:36+0200 jenkins[3113576]: java.lang.NoSuchMethodError: 'void hudson.security.ChainedServletFilter.<init>(javax.servlet.Filter[])'                                                                 
2024-09-10T06:57:36+0200 jenkins[3113576]:         at PluginClassLoader for oic-auth//org.jenkinsci.plugins.oic.OicSecurityRealm.createFilter(OicSecurityRealm.java:828)                                           
2024-09-10T06:57:36+0200 jenkins[3113576]:         at hudson.security.SecurityRealm.createFilter(SecurityRealm.java:626)                                                                                           
2024-09-10T06:57:36+0200 jenkins[3113576]:         at hudson.security.HudsonFilter.reset(HudsonFilter.java:145)                                                                                                    
2024-09-10T06:57:36+0200 jenkins[3113576]:         at jenkins.model.Jenkins.resetFilter(Jenkins.java:2820)                                                                                                         
2024-09-10T06:57:36+0200 jenkins[3113576]:         at jenkins.model.Jenkins.setSecurityRealm(Jenkins.java:2802)                                                                                                    
2024-09-10T06:57:36+0200 jenkins[3113576]:         at hudson.security.GlobalSecurityConfiguration.configure(GlobalSecurityConfiguration.java:135)                                                                  
2024-09-10T06:57:36+0200 jenkins[3113576]:         at hudson.security.GlobalSecurityConfiguration.doConfigure(GlobalSecurityConfiguration.java:116)                                                                
2024-09-10T06:57:36+0200 jenkins[3113576]:         at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)                                                                           
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:484)                                                                                        
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:497)                                                                                      
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:218)                                                                                                
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.SelectionInterceptedFunction$Adapter.invoke(SelectionInterceptedFunction.java:37)                                                        
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.verb.HttpVerbInterceptor.invoke(HttpVerbInterceptor.java:48)                                                                             
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.SelectionInterceptedFunction.bindAndInvoke(SelectionInterceptedFunction.java:26)                                                         
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:140)                                                                                
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.MetaClass$12.doDispatch(MetaClass.java:686)                                                                                              
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:61)                                                                                
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:800)                                                                                                      
2024-09-10T06:57:36+0200 jenkins[3113576]: Caused: jakarta.servlet.ServletException                                                                                                                                
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:851)                                                                                                      
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Stapler.invoke(Stapler.java:938)                                                                                                         
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:590)                                                                                                
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:800)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Stapler.invoke(Stapler.java:938)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:871)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Stapler.invoke(Stapler.java:938)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.MetaClass$10.dispatch(MetaClass.java:590)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:800)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Stapler.invoke(Stapler.java:938)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Stapler.invoke(Stapler.java:721)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at org.kohsuke.stapler.Stapler.service(Stapler.java:253)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at Jenkins Main ClassLoader//jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.ServletHolder.handle(ServletHolder.java:765)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at Jenkins Main ClassLoader//org.eclipse.jetty.ee9.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1668)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:204)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.FilterChainWrapper$2.doFilter(FilterChainWrapper.java:53)
2024-09-10T06:57:36+0200 jenkins[3113576]: Caused: javax.servlet.ServletException
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.ServletExceptionWrapper.fromJakartaServletException(ServletExceptionWrapper.java:14)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.FilterChainWrapper$2.doFilter(FilterChainWrapper.java:62)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at PluginClassLoader for sse-gateway//org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:248)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.FilterWrapper$1.doFilter(FilterWrapper.java:42)
2024-09-10T06:57:36+0200 jenkins[3113576]: Caused: jakarta.servlet.ServletException
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.ServletExceptionWrapper.toJakartaServletException(ServletExceptionWrapper.java:9)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.FilterWrapper$1.doFilter(FilterWrapper.java:53)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:201)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.FilterChainWrapper$2.doFilter(FilterChainWrapper.java:53)
2024-09-10T06:57:36+0200 jenkins[3113576]: Caused: javax.servlet.ServletException
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.ServletExceptionWrapper.toJakartaServletException(ServletExceptionWrapper.java:9)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.FilterWrapper$1.doFilter(FilterWrapper.java:53)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:201)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.FilterChainWrapper$2.doFilter(FilterChainWrapper.java:53)
2024-09-10T06:57:36+0200 jenkins[3113576]: Caused: javax.servlet.ServletException
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.ServletExceptionWrapper.fromJakartaServletException(ServletExceptionWrapper.java:14)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.FilterChainWrapper$2.doFilter(FilterChainWrapper.java:62)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at PluginClassLoader for atlassian-bitbucket-server-integration//com.atlassian.bitbucket.jenkins.internal.applink.oauth.serviceprovider.auth.OAuth1aRequestFilte
r.doFilter(OAuth1aRequestFilter.java:91)
2024-09-10T06:57:36+0200 jenkins[3113576]:         at io.jenkins.servlet.FilterWrapper$1.doFilter(FilterWrapper.java:42)
2024-09-10T06:57:36+0200 jenkins[3113576]: Caused: jakarta.servlet.ServletException

```

### Anything else?

After the update the configuration of it  was complete lost.

**Comment by eva-mueller-coremedia** [comment] 2024-09-10 06:03
Is this a duplicate of https://github.com/jenkinsci/oic-auth-plugin/issues/387?

**Comment by tuxmaster5000** [comment] 2024-09-10 06:30
No, because in my case jenkins itself will start.  Bu nobody can log in.

**Comment by alecharp** [comment] 2024-09-10 08:49
@tuxmaster5000 sure but it should be the same fix. Could you try the incremental build of https://github.com/jenkinsci/jenkins/pull/9696?

**Comment by tuxmaster5000** [comment] 2024-09-10 10:19
Yes of curse, but where can I download it?

**Comment by alecharp** [comment] 2024-09-10 10:35
You can find the latest war file (at the moment) following those links: https://github.com/jenkinsci/jenkins/runs/29909838835

**Comment by tuxmaster5000** [comment] 2024-09-10 12:12
Thanks, with this war file no class not found exception happens, but now an algorithm looks missing:
`2024-09-10T14:09:50+0200 jenkins[3309604]: com.google.api.client.auth.openidconnect.IdTokenVerifier$VerificationException: Unexpected signing algorithm PS512: expected either RS256 or ES256      `

**Comment by basil** [comment] 2024-09-10 14:19
I am closing this ticket as a duplicate. If issues are still encountered with the 2.476 weekly release, file a _separate_ ticket with the full exception stack trace and details about how to reproduce the issue from scratch.

**Comment by basil** [comment] 2024-09-10 14:20
Duplicate of #387

**Closed** 2024-09-10 14:20 UTC
Labels: bug

**Comment by tuxmaster5000** [comment] 2024-09-13 10:31
It is only the half, because before I never see the exception before and the plugin was working.
Now it fails.

**Comment by basil** [comment] 2024-09-13 18:02
See https://github.com/jenkinsci/oic-auth-plugin/issues/393#issuecomment-2340970918.
