### ISSUE TITLE
Few Issues with Keycloak

### ISSUE THREAD

**Issue by vikas027** [jenkinsci/oic-auth-plugin#14] opened 2017-07-14 13:07 UTC
### Environment

- [Keycloak](https://github.com/keycloak) 3.2.0
- Jenkins 2.69
- [OpenId Connect Authentication Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Openid+Connect+Authentication+Plugin) 1.0

### Problem
Thanks for the plugin. I am able to log in using my user in Keycloak but have few issues.

 

- I am trying to save _preferrred_username_ in _User name field_, it allows me to save, but when I re-open it, somehow _sub_ gets populated.

![2017-07-14_22-58-23](https://user-images.githubusercontent.com/6998650/28213109-fbe02308-68e7-11e7-899d-5463916fda23.png)

- Unable to _log out_. When hit 'log out', page refreshes and I get redirected to home page but doesn't get logged out

- Username is not populated in top right, instead, the long ID of Keycloak is being displayed
![2017-07-14_23-03-05](https://user-images.githubusercontent.com/6998650/28213252-a0ab44f8-68e8-11e7-8c6d-0946348d0923.png)

### Probable Solution (to few of above)

This [link](http://devopsku.be/setup/jenkins-keycloak/) has few other options like _UserInfo server url_ and _Logout url_
Somehow, I do not have these options. May be these were in older versions and were removed in v1.0?

**Comment by mateothegreat** [comment] 2018-02-10 08:28
Confirmed issue Jenkins ver. 2.105

**Comment by mateothegreat** [comment] 2018-02-10 08:34
Duped by #7 

Solution for now is to update config.xml:
<userNameField>sub</userNameField>
to 
<userNameField>preferred_username</userNameField>

**Comment by mjmbischoff** [comment] 2018-02-28 18:16
#7 is closed as 1.1 is released, so closing this as well.

**Closed by mjmbischoff** 2018-02-28 18:16 UTC
