### ISSUE TITLE
Unable access Jenkins API with basic auth

### ISSUE THREAD

**Issue by roicostas** [jenkinsci/oic-auth-plugin#25] opened 2018-03-28 17:31 UTC
I am trying to access Jenkins API using user and password but I get an authentication error. Example with curl:
```
$ curl --user admin:admin https://jenkins/api/json?depth=1
...
<h2>HTTP ERROR 401</h2>
<p>Problem accessing /api/json. Reason:
<pre>    Invalid password/token for user: admin</pre></p>
...
```
However if I connect using the user API token everything works fine:
`curl --user admin:<token> https://jenkins/api/json?depth=1`

Is this behavior expected? 

The plugin works fine through the web ui.

**Comment by mjmbischoff** [comment] 2018-03-28 18:16
I had no expectation of behavior as I hadn't considered the use-case yet. Thinking about this:

Technically authentication is completely delegated to the openid provider. ("a user claims to be x, openid provider what say you, is user this x?" and then jenkins goes with whatever it the provider said) As a security feature you never share your credentials(in your case username / password) with the jenkins instance. If using the username / password with the api would work then that means it passes through the jenkins instance. 

Depending on your setup you might well not care because you might have full control of both and faith in Jenkins security. 

Openid connect also doesn't dictate the actually, eventual, authentication method or amount of factors used. For example depending on your openid provider implementation this could be a hardware token, OTP, Security patterns or even delegate it again to something else by using for example SAML

So there might not be a user / password combination to pass on.

I'll hope this explanation helps a bit to understand why I think we can't support this.

I'll leave this open so you can ask further questions if you have them and so I can give this issue some more thought.

**Comment by mjmbischoff** [comment] 2018-04-02 11:25
Yeah considering the a fore mentioned it is intentional behavior. It does make sense to add this to the plugin documentation, which I'll track under this issue.

**Comment by roicostas** [comment] 2018-04-03 09:32
OpenId connect protocol supports that the user shares its credentials with the client. See https://tools.ietf.org/html/rfc6749#section-1.3.3 . This would ease accessing Jenkins API with user credentials directly. Of course, it only makes sense with a trusted Jenkins instance.

I am working around it authenticating through OpenId Connect first to get the authentication token.

**Comment by roicostas** [comment] 2018-04-03 09:38
My mistake, this kind of authentication is part of OAuth 2.0 but not OpenID connect

**Comment by mjmbischoff** [comment] 2018-04-03 14:30
Just to clarify, by authentication token you mean the API token right? ( https://wiki.jenkins.io/display/JENKINS/Authenticating+scripted+clients )

**Comment by mjmbischoff** [comment] 2018-04-17 12:02
Yes that's expected behavior as we do not hook into that part of Jenkins yet. The API token bit probably works because we implement the default interface.

**Comment by mjmbischoff** [comment] 2018-05-15 00:32
added my ramblings to the wiki page feel free to success improvements, closing this issue for now.

**Closed by mjmbischoff** 2018-05-15 00:32 UTC

**Comment by diaojunxian** [comment] 2018-07-08 02:56
@mjmbischoff as I use the userid and api token, the curl command is `curl --user <userid>:<api token> http://127.0.0.1:8080/job/test/3/consoleText/api/json`, the output is 
```
Access Denied and the <userid> Not all /read permissions
```
but the userid is the admin privilege，why it happend ?

**Comment by ChristianCiach** [comment] 2020-11-25 11:38
We see the exact same issue as @diaojunxian.
